/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.Jogo;
import control.QuatroEmLinha;
import helpers.GFG;
import model.Algoritmo;

/**
 *
 * @author Elizeu
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        puzzle8algoritmo = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        inicial_11 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        inicial_12 = new javax.swing.JTextField();
        inicial_13 = new javax.swing.JTextField();
        inicial_23 = new javax.swing.JTextField();
        inicial_22 = new javax.swing.JTextField();
        inicial_21 = new javax.swing.JTextField();
        inicial_31 = new javax.swing.JTextField();
        inicial_32 = new javax.swing.JTextField();
        inicial_33 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        objetivo_11 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        objetivo_12 = new javax.swing.JTextField();
        objetivo_13 = new javax.swing.JTextField();
        objetivo_23 = new javax.swing.JTextField();
        objetivo_22 = new javax.swing.JTextField();
        objetivo_21 = new javax.swing.JTextField();
        objetivo_31 = new javax.swing.JTextField();
        objetivo_32 = new javax.swing.JTextField();
        objetivo_33 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        JRdBtnCustoUniforme = new javax.swing.JRadioButton();
        JRdBtnHeurPrecisa = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        JRdBtnHeurSimples = new javax.swing.JRadioButton();
        jBtnJogar8Puzzle = new javax.swing.JButton();
        tabuleiro1 = new view.Tabuleiro();
        mensagem = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("T1 - Métodos de Busca");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        inicial_11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        inicial_11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inicial_11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inicial_11KeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tabuleiro Inicial");

        inicial_12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        inicial_12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inicial_12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inicial_12KeyReleased(evt);
            }
        });

        inicial_13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        inicial_13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inicial_13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inicial_13KeyReleased(evt);
            }
        });

        inicial_23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        inicial_23.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inicial_23.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inicial_23KeyReleased(evt);
            }
        });

        inicial_22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        inicial_22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inicial_22.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inicial_22KeyReleased(evt);
            }
        });

        inicial_21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        inicial_21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inicial_21.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inicial_21KeyReleased(evt);
            }
        });

        inicial_31.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        inicial_31.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inicial_31.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inicial_31KeyReleased(evt);
            }
        });

        inicial_32.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        inicial_32.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inicial_32.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inicial_32KeyReleased(evt);
            }
        });

        inicial_33.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        inicial_33.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inicial_33.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inicial_33KeyReleased(evt);
            }
        });

        jButton1.setText("Setar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Pré-definido 1");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Pré-definido 2");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Pré-definido 3");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(inicial_11, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inicial_12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inicial_13, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(inicial_21, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inicial_22, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inicial_23, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(inicial_31, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inicial_32, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inicial_33, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jButton1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inicial_11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inicial_12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inicial_13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inicial_21, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inicial_22, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inicial_23, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inicial_31, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inicial_32, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inicial_33, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        objetivo_11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        objetivo_11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        objetivo_11.setText("1");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Objetivo");

        objetivo_12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        objetivo_12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        objetivo_12.setText("2");

        objetivo_13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        objetivo_13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        objetivo_13.setText("3");

        objetivo_23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        objetivo_23.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        objetivo_23.setText("6");

        objetivo_22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        objetivo_22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        objetivo_22.setText("5");

        objetivo_21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        objetivo_21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        objetivo_21.setText("4");

        objetivo_31.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        objetivo_31.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        objetivo_31.setText("7");

        objetivo_32.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        objetivo_32.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        objetivo_32.setText("8");

        objetivo_33.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        objetivo_33.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jButton2.setText("Setar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(objetivo_11, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(objetivo_12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(objetivo_13, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(objetivo_21, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(objetivo_22, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(objetivo_23, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(objetivo_31, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(objetivo_32, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(objetivo_33, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(objetivo_11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(objetivo_12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(objetivo_13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(objetivo_21, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(objetivo_22, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(objetivo_23, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(objetivo_31, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(objetivo_32, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(objetivo_33, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        puzzle8algoritmo.add(JRdBtnCustoUniforme);
        JRdBtnCustoUniforme.setSelected(true);
        JRdBtnCustoUniforme.setText("Custo Uniforme");

        puzzle8algoritmo.add(JRdBtnHeurPrecisa);
        JRdBtnHeurPrecisa.setText("A* Heurística Precisa");

        jLabel3.setText("Algoritmo");

        puzzle8algoritmo.add(JRdBtnHeurSimples);
        JRdBtnHeurSimples.setText("A* Heurística Simples");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JRdBtnHeurPrecisa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addComponent(JRdBtnHeurSimples, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JRdBtnCustoUniforme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JRdBtnCustoUniforme)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JRdBtnHeurSimples)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JRdBtnHeurPrecisa))
        );

        jBtnJogar8Puzzle.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jBtnJogar8Puzzle.setText("Jogar");
        jBtnJogar8Puzzle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnJogar8PuzzleActionPerformed(evt);
            }
        });

        tabuleiro1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout tabuleiro1Layout = new javax.swing.GroupLayout(tabuleiro1);
        tabuleiro1.setLayout(tabuleiro1Layout);
        tabuleiro1Layout.setHorizontalGroup(
            tabuleiro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        tabuleiro1Layout.setVerticalGroup(
            tabuleiro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mensagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBtnJogar8Puzzle, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addComponent(tabuleiro1, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBtnJogar8Puzzle, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tabuleiro1, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mensagem, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("8 Puzzle", jPanel1);

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton7.setText("Jogar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(347, 347, 347)
                .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                .addGap(40, 40, 40))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(220, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("4 em linha", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public String max1numro(String numero) {
        char[] n = numero.toCharArray();
        String retorno = n[n.length - 1] + "";
        return retorno;
    }

    private void inicial_11KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inicial_11KeyReleased
        // TODO add your handling code here:
        inicial_11.setText(this.max1numro(inicial_11.getText()));
    }//GEN-LAST:event_inicial_11KeyReleased

    private void inicial_12KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inicial_12KeyReleased
        // TODO add your handling code here:
        inicial_12.setText(this.max1numro(inicial_12.getText()));
    }//GEN-LAST:event_inicial_12KeyReleased

    private void inicial_13KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inicial_13KeyReleased
        // TODO add your handling code here:
        inicial_13.setText(this.max1numro(inicial_13.getText()));
    }//GEN-LAST:event_inicial_13KeyReleased

    private void inicial_21KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inicial_21KeyReleased
        // TODO add your handling code here:
        inicial_21.setText(this.max1numro(inicial_21.getText()));
    }//GEN-LAST:event_inicial_21KeyReleased

    private void inicial_22KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inicial_22KeyReleased
        // TODO add your handling code here:
        inicial_22.setText(this.max1numro(inicial_22.getText()));
    }//GEN-LAST:event_inicial_22KeyReleased

    private void inicial_23KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inicial_23KeyReleased
        // TODO add your handling code here:
        inicial_23.setText(this.max1numro(inicial_23.getText()));
    }//GEN-LAST:event_inicial_23KeyReleased

    private void inicial_31KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inicial_31KeyReleased
        // TODO add your handling code here:
        inicial_31.setText(this.max1numro(inicial_31.getText()));
    }//GEN-LAST:event_inicial_31KeyReleased

    private void inicial_32KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inicial_32KeyReleased
        // TODO add your handling code here:
        inicial_32.setText(this.max1numro(inicial_32.getText()));
    }//GEN-LAST:event_inicial_32KeyReleased

    private void inicial_33KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inicial_33KeyReleased
        // TODO add your handling code here:
        inicial_33.setText(this.max1numro(inicial_33.getText()));
    }//GEN-LAST:event_inicial_33KeyReleased

    private boolean validaMatriz(int[][] matriz) {
        boolean[] validacao = new boolean[9];

        for (int i = 0; i < 9; i++) {
            int linha = i / 3;
            int coluna = (int) i % 3;

            int n = matriz[linha][coluna];

            if (validacao[n]) {
                return false;
            } else {
                validacao[n] = true;
            }
        }

        return true;
    }

    private int nOrZero(javax.swing.JTextField tf) {
        return tf.getText().equals("") ? 0 : Integer.parseInt(tf.getText());
    }

    public Tabuleiro getTabuleiro() {
        return tabuleiro1;
    }
 
    public void fimDeJogo8Puzzle(){
        jBtnJogar8Puzzle.setEnabled(true);   
    }
    
    public void setMensagem(String msg) {
        this.mensagem.setText(msg);
    }
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        int matriz[][] = {
            {nOrZero(inicial_11), nOrZero(inicial_12), nOrZero(inicial_13)},
            {nOrZero(inicial_21), nOrZero(inicial_22), nOrZero(inicial_23)},
            {nOrZero(inicial_31), nOrZero(inicial_32), nOrZero(inicial_33)}
        };

        if (!this.validaMatriz(matriz)) {
            PopUps.showMessage("Tabuleiro incorreto");
            jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        } else {
            jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int matriz[][] = {
            {nOrZero(objetivo_11), nOrZero(objetivo_12), nOrZero(objetivo_13)},
            {nOrZero(objetivo_21), nOrZero(objetivo_22), nOrZero(objetivo_23)},
            {nOrZero(objetivo_31), nOrZero(objetivo_32), nOrZero(objetivo_33)}
        };

        if (!this.validaMatriz(matriz)) {
            PopUps.showMessage("Tabuleiro incorreto");
            jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        } else {
            jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
//        {8, 6, 7},
//        {2, 5, 4},
//        {3, 0, 1}
        inicial_11.setText("8");
        inicial_12.setText("6");
        inicial_13.setText("7");

        inicial_21.setText("2");
        inicial_22.setText("5");
        inicial_23.setText("4");

        inicial_31.setText("3");
        inicial_32.setText("");
        inicial_33.setText("1");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
//            {8, 5, 2},
//            {7, 6, 4},
//            {3, 1, 0}
        inicial_11.setText("8");
        inicial_12.setText("5");
        inicial_13.setText("2");

        inicial_21.setText("7");
        inicial_22.setText("6");
        inicial_23.setText("4");

        inicial_31.setText("3");
        inicial_32.setText("1");
        inicial_33.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
//            {8, 1, 2},
//            {0, 4, 3},
//            {7, 6, 5}
        inicial_11.setText("8");
        inicial_12.setText("1");
        inicial_13.setText("2");

        inicial_21.setText("");
        inicial_22.setText("4");
        inicial_23.setText("3");

        inicial_31.setText("7");
        inicial_32.setText("6");
        inicial_33.setText("5");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jBtnJogar8PuzzleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnJogar8PuzzleActionPerformed
        // TODO add your handling code here:

        int inicial[][] = {
            {nOrZero(inicial_11), nOrZero(inicial_12), nOrZero(inicial_13)},
            {nOrZero(inicial_21), nOrZero(inicial_22), nOrZero(inicial_23)},
            {nOrZero(inicial_31), nOrZero(inicial_32), nOrZero(inicial_33)}
        };

        int objetivo[][] = {
            {nOrZero(objetivo_11), nOrZero(objetivo_12), nOrZero(objetivo_13)},
            {nOrZero(objetivo_21), nOrZero(objetivo_22), nOrZero(objetivo_23)},
            {nOrZero(objetivo_31), nOrZero(objetivo_32), nOrZero(objetivo_33)}
        };

        if (!this.validaMatriz(inicial)) {
            PopUps.showMessage("Tabuleiro Inicial incorreto");
            jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
            return;
        } else {
            jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        }

        if (!this.validaMatriz(objetivo)) {
            PopUps.showMessage("Tabuleiro Objetivo incorreto");
            jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
            return;
        } else {
            jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        }
        if (GFG.isSolvable(inicial)) {
            //cria a GUI para o tabuleiro
//            Tabuleiro tabuleiro = new Tabuleiro(3, 550, 30);
//            SwingUtilities.invokeLater(() -> {
//                javax.swing.JFrame frame = new javax.swing.JFrame();
//                frame.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
//                frame.setTitle("Jogo 8-puzzle");
//                frame.setResizable(false);
//                frame.add(tabuleiro, java.awt.BorderLayout.CENTER);
//                frame.pack();
//                // centralizar a tela
//                frame.setLocationRelativeTo(null);
//                frame.setVisible(true);
//            });
//            if (1 == 2) {
//                Jogo j = new Jogo(objetivo, inicial, tabuleiro);
//                j.run();
//            } else {
            
            Algoritmo algoritmo = this.JRdBtnCustoUniforme.isSelected() ? Algoritmo.CUSTO_UNIFORME : (this.JRdBtnHeurSimples.isSelected() ? Algoritmo.A_ESTRELA_SIMPLES : Algoritmo.A_ESTRELA_PRECISA);
            
            Jogo j = new Jogo(objetivo, inicial, this);
            
            j.setAlgoritmo(algoritmo);
            j.start();
            jBtnJogar8Puzzle.setEnabled(false);
            
//            }
        } else {
            PopUps.showMessage("O estado inicial não é solucionável!");
        }

    }//GEN-LAST:event_jBtnJogar8PuzzleActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        
        QuatroEmLinha j2 = new QuatroEmLinha();
        j2.verificaVencedor();
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new TelaInicial().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton JRdBtnCustoUniforme;
    private javax.swing.JRadioButton JRdBtnHeurPrecisa;
    private javax.swing.JRadioButton JRdBtnHeurSimples;
    private javax.swing.JTextField inicial_11;
    private javax.swing.JTextField inicial_12;
    private javax.swing.JTextField inicial_13;
    private javax.swing.JTextField inicial_21;
    private javax.swing.JTextField inicial_22;
    private javax.swing.JTextField inicial_23;
    private javax.swing.JTextField inicial_31;
    private javax.swing.JTextField inicial_32;
    private javax.swing.JTextField inicial_33;
    private javax.swing.JButton jBtnJogar8Puzzle;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel mensagem;
    private javax.swing.JTextField objetivo_11;
    private javax.swing.JTextField objetivo_12;
    private javax.swing.JTextField objetivo_13;
    private javax.swing.JTextField objetivo_21;
    private javax.swing.JTextField objetivo_22;
    private javax.swing.JTextField objetivo_23;
    private javax.swing.JTextField objetivo_31;
    private javax.swing.JTextField objetivo_32;
    private javax.swing.JTextField objetivo_33;
    private javax.swing.ButtonGroup puzzle8algoritmo;
    private view.Tabuleiro tabuleiro1;
    // End of variables declaration//GEN-END:variables


}
